name: dshell
description: A bash replacement allowing you to write bash like scripts using dart and run them directly from the cli.
version: 1.0.23
homepage: https://github.com/bsutton/dshell

environment:
 sdk: '>=2.6.0 <3.0.0'

dependencies:
  args: ^1.5.2
  collection: ^1.14.12
  file_utils: ^0.1.3
  path: ^1.6.4
  yaml: ^2.2.0
  intl: ^0.16.0
  logger: ^0.8.0
  recase: ^2.0.1
  money2: ^1.0.5
  pubspec: ^0.1.2
  file: ^5.1.0
  equatable: ^1.0.1

dev_dependencies:
  test: ^1.6.0
  pedantic: ^1.8.0

  ##
  ## To compile
  ## pub global activate --source path .
executables:
  dshell: dshell
