name: dshell
description: A bash replacement allowing you to write bash like scripts using dart and run them directly from the cli.
version: 1.0.8
homepage: https://github.com/bsutton/dshell
authors: 
  - bsutton <bsutton@noojee.com.au>

environment:
 sdk: '>=2.6.0 <3.0.0'

dependencies:
  args: ^1.5.2
  file_utils: ^0.1.3
  path: ^1.6.4
  pedantic: ^1.8.0
  yaml: ^2.2.0
  intl: ^0.16.0
  logger: ^0.7.0+2
  recase: ^2.0.1
  money2: ^1.0.5
  file: ^5.1.0

dev_dependencies:
  test: ^1.6.0

  ##
  ## To compile
  ## pub global activate --source path .
executables:
  dshell: dshell
